# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35e59d5a4757ce96a4642794192c49fa701e54a2a98c4cf1109370971c36e87b2489a97441e056efa533403666fd3a9ad5044023cb6928f39a152f2903202188

test:
  secret_key_base: fafcc0e971707a790151d54155058e609b98594a86b02115dca3bf2eaee79594ec41e9d72ed9281b6ca2ac09e9d8f3edcee1919a6b7c2d7ee8ae59a87dcd291c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
